name = "image-resizer"
main = "./resizer.js"
compatibility_date = "2021-09-21"

[dev]
port = 9001
local_protocol="http"
upstream_protocol="https"

[env.staging]
name = "staging-resizer"
vars = { ENVIRONMENT = "staging" }
workers_dev = true

[env.prod]
name = "prod-resizer"
vars = { ENVIRONMENT = "production" }
route = "*erfianugrah.com/content/images/*"