name = "image-resizer"
main = "./resizer.mjs"
compatibility_date = "2021-09-21"
account_id = env.ACCOUNT_ID 
send_metrics = false

[dev]
port = 9001
local_protocol="http"
upstream_protocol="https"

[env.staging]
name = "staging-resizer"
vars = { ENVIRONMENT = "staging" }
workers_dev = true

[env.prod]
name = "prod-resizer"
vars = { ENVIRONMENT = "production" }
routes = [
    { pattern = "example.com/images/* zone_id = env.ZONE_ID },
]
