# Cloudflare Image Resizing Worker Configuration
# ---
# This worker provides dynamic image resizing capabilities using 
# Cloudflare's Image Resizing service.

name = "image-resizer"
main = "src/index.js"
compatibility_date = "2025-01-01"
account_id = "25f21f141824546aa72c74451a11b419"

# Resource limits to prevent unexpected billing
[limits]
cpu_ms = 50
memory_mb = 128

# Observability settings
[observability]
enabled = true
head_sampling_rate = 1

# Development server configuration
[dev]
port = 9001
local_protocol = "http"
upstream_protocol = "https"

#
# Environment Configurations
#

# Direct mode deployment (worker runs on the bucket)
[env.direct]
name = "direct-resizer"

[env.direct.vars]
ENVIRONMENT = "development"
DEPLOYMENT_MODE = "direct"
ROUTE_DERIVATIVES = "{\"profile-pictures\":\"thumbnail\",\"hero-banners\":\"header\",\"header\":\"header\",\"thumbnail\":\"thumbnail\"}"
VERSION = "1.1.0"
FALLBACK_BUCKET = "https://cdn.erfianugrah.com"

[[env.direct.routes]]
pattern = "dev-direct.images.erfi.dev/*"
zone_id = "d6260a9cd0c27db1e9c0a453b2e4761e"

# Remote mode deployment (worker fetches from remote buckets)
[env.remote]
name = "remote-resizer"

[env.remote.vars]
ENVIRONMENT = "development"
DEPLOYMENT_MODE = "remote"
REMOTE_BUCKETS = "{\"default\":\"https://cdn.erfianugrah.com\"}"
ROUTE_DERIVATIVES = "{\"profile-pictures\":\"thumbnail\",\"hero-banners\":\"header\",\"header\":\"header\",\"thumbnail\":\"thumbnail\"}"
PATH_TRANSFORMS = "{\"images\":{\"prefix\":\"\",\"removePrefix\":true}}"
VERSION = "1.1.0"
FALLBACK_BUCKET = "https://cdn.erfianugrah.com"

[[env.remote.routes]]
pattern = "dev-remote.images.erfi.dev/*"
zone_id = "d6260a9cd0c27db1e9c0a453b2e4761e"

# Staging environment
[env.staging]
name = "staging-resizer"

[env.staging.vars]
ENVIRONMENT = "staging"
DEPLOYMENT_MODE = "remote"
REMOTE_BUCKETS = "{\"default\":\"https://cdn.erfianugrah.com\"}"
ROUTE_DERIVATIVES = "{\"profile-pictures\":\"thumbnail\",\"hero-banners\":\"header\",\"header\":\"header\",\"thumbnail\":\"thumbnail\"}"
PATH_TRANSFORMS = "{\"images\":{\"prefix\":\"\",\"removePrefix\":true}}"
VERSION = "1.1.0"
FALLBACK_BUCKET = "https://cdn.erfianugrah.com"

[[env.staging.routes]]
pattern = "staging.images.erfi.dev/*"
zone_id = "d6260a9cd0c27db1e9c0a453b2e4761e"

# Production environment
[env.prod]
name = "prod-resizer"

[env.prod.vars]
ENVIRONMENT = "production"
DEPLOYMENT_MODE = "remote"
REMOTE_BUCKETS = "{\"default\":\"https://cdn.erfianugrah.com\"}"
ROUTE_DERIVATIVES = "{\"profile-pictures\":\"thumbnail\",\"hero-banners\":\"header\",\"header\":\"header\",\"thumbnail\":\"thumbnail\"}"
PATH_TRANSFORMS = "{\"images\":{\"prefix\":\"\",\"removePrefix\":true}}"
VERSION = "1.1.0"
FALLBACK_BUCKET = "https://cdn.erfianugrah.com"

[[env.prod.routes]]
pattern = "images.erfi.dev/*"
zone_id = "d6260a9cd0c27db1e9c0a453b2e4761e"
