name = "image-resizer"
type = "javascript"

[dev]
ip = "0.0.0.0"
port = 9000
local_protocol="http"
upstream_protocol="https"

[env.staging]
name = "staging-resizer"
vars = { ENVIRONMENT = "staging" }
workers_dev = true

[env.prod]
name = "prod-resizer"
vars = { ENVIRONMENT = "production" }
route = "*erfianugrah.com/wp-content/uploads/*"