# Cloudflare Image Resizing Worker Configuration
# ---
# This worker provides dynamic image resizing capabilities using 
# Cloudflare's Image Resizing service.

name = "image-resizer"
main = "src/index.js"
compatibility_date = "2025-01-01"
account_id = "25f21f141824546aa72c74451a11b419"

# Resource limits to prevent unexpected billing
[limits]
cpu_ms = 50
memory_mb = 128

# Observability settings
[observability]
enabled = true
head_sampling_rate = 1

# Development server configuration
[dev]
port = 9001
local_protocol = "http"
upstream_protocol = "https"

#
# Environment Configurations
#

# Direct mode deployment (worker runs on the bucket)
[env.direct]
name = "direct-resizer"

[env.direct.vars]
ENVIRONMENT = "development"
DEPLOYMENT_MODE = "direct"
VERSION = "1.1.0"
FALLBACK_BUCKET = "https://cdn.erfianugrah.com"

# Centralized logging configuration
LOGGING_CONFIG = '''
{
  "level": "DEBUG",
  "includeTimestamp": true,
  "enableStructuredLogs": true
}
'''

# Centralized debug headers configuration
DEBUG_HEADERS_CONFIG = '''
{
  "enabled": true,
  "prefix": "debug-",
  "includeHeaders": ["ir", "cache", "mode", "client-hints", "ua", "device"],
  "specialHeaders": {
    "x-processing-mode": true,
    "x-size-source": true,
    "x-actual-width": true,
    "x-responsive-sizing": true
  }
}
'''

# Predefined image transformation templates
DERIVATIVE_TEMPLATES = '''
{
  "header": {
    "width": 1600,
    "height": 73,
    "quality": 80,
    "fit": "scale-down",
    "metadata": "copyright"
  },
  "thumbnail": {
    "width": 320,
    "height": 150,
    "quality": 85,
    "fit": "scale-down",
    "metadata": "copyright",
    "sharpen": 1
  },
  "avatar": {
    "width": 180,
    "height": 180,
    "quality": 90,
    "fit": "cover",
    "metadata": "none",
    "gravity": "face"
  },
  "product": {
    "width": 800,
    "height": 800,
    "quality": 85,
    "fit": "contain",
    "background": "white"
  }
}
'''

# Path-based derivative mappings
PATH_TEMPLATES = '''
{
  "profile-pictures": "avatar",
  "hero-banners": "header",
  "header": "header",
  "thumbnail": "thumbnail",
  "avatars": "avatar",
  "products": "product"
}
'''

[[env.direct.routes]]
pattern = "dev-direct.images.erfi.dev/*"
zone_id = "d6260a9cd0c27db1e9c0a453b2e4761e"

# Remote mode deployment (worker fetches from remote buckets)
[env.remote]
name = "remote-resizer"

[env.remote.vars]
ENVIRONMENT = "development"
DEPLOYMENT_MODE = "remote"
VERSION = "1.1.0"
FALLBACK_BUCKET = "https://cdn.erfianugrah.com"

# Centralized logging configuration
LOGGING_CONFIG = '''
{
  "level": "DEBUG",
  "includeTimestamp": true,
  "enableStructuredLogs": true
}
'''

# Centralized debug headers configuration
DEBUG_HEADERS_CONFIG = '''
{
  "enabled": true,
  "prefix": "debug-",
  "includeHeaders": ["ir", "cache", "mode", "client-hints", "ua", "device"],
  "specialHeaders": {
    "x-processing-mode": true,
    "x-size-source": true, 
    "x-actual-width": true,
    "x-responsive-sizing": true
  }
}
'''

# Predefined image transformation templates
DERIVATIVE_TEMPLATES = '''
{
  "header": {
    "width": 1600,
    "height": 73,
    "quality": 80,
    "fit": "scale-down",
    "metadata": "copyright"
  },
  "thumbnail": {
    "width": 320,
    "height": 150,
    "quality": 85,
    "fit": "scale-down",
    "metadata": "copyright",
    "sharpen": 1
  },
  "avatar": {
    "width": 180,
    "height": 180,
    "quality": 90,
    "fit": "cover",
    "metadata": "none",
    "gravity": "face"
  },
  "product": {
    "width": 800,
    "height": 800,
    "quality": 85,
    "fit": "contain",
    "background": "white"
  }
}
'''

# Path-based derivative mappings
PATH_TEMPLATES = '''
{
  "profile-pictures": "avatar",
  "hero-banners": "header",
  "header": "header",
  "thumbnail": "thumbnail",
  "avatars": "avatar",
  "products": "product"
}
'''

# Remote bucket configuration
REMOTE_BUCKETS = '''
{
  "default": "https://cdn.erfianugrah.com"
}
'''

# Path transformation rules for remote buckets
PATH_TRANSFORMS = '''
{
  "images": {
    "prefix": "",
    "removePrefix": true
  },
  "assets": {
    "prefix": "img/", 
    "removePrefix": true
  },
  "content": {
    "prefix": "content-images/",
    "removePrefix": true
  }
}
'''

[[env.remote.routes]]
pattern = "dev-remote.images.erfi.dev/*"
zone_id = "d6260a9cd0c27db1e9c0a453b2e4761e"

# Staging environment
[env.staging]
name = "staging-resizer"

[env.staging.vars]
ENVIRONMENT = "staging"
DEPLOYMENT_MODE = "remote"
VERSION = "1.1.0"
FALLBACK_BUCKET = "https://cdn.erfianugrah.com"

# Centralized logging configuration - slightly less verbose for staging
LOGGING_CONFIG = '''
{
  "level": "INFO",
  "includeTimestamp": true,
  "enableStructuredLogs": true
}
'''

# Centralized debug headers configuration - enabled but limited for staging
DEBUG_HEADERS_CONFIG = '''
{
  "enabled": true,
  "prefix": "debug-",
  "includeHeaders": ["ir", "cache", "mode"],
  "allowedEnvironments": ["staging", "development"]
}
'''

# Predefined image transformation templates (same as other environments)
DERIVATIVE_TEMPLATES = '''
{
  "header": {
    "width": 1600,
    "height": 73,
    "quality": 80,
    "fit": "scale-down",
    "metadata": "copyright"
  },
  "thumbnail": {
    "width": 320,
    "height": 150,
    "quality": 85,
    "fit": "scale-down",
    "metadata": "copyright",
    "sharpen": 1
  },
  "avatar": {
    "width": 180,
    "height": 180,
    "quality": 90,
    "fit": "cover",
    "metadata": "none",
    "gravity": "face"
  },
  "product": {
    "width": 800,
    "height": 800,
    "quality": 85,
    "fit": "contain",
    "background": "white"
  }
}
'''

# Path-based derivative mappings (same as other environments)
PATH_TEMPLATES = '''
{
  "profile-pictures": "avatar",
  "hero-banners": "header",
  "header": "header",
  "thumbnail": "thumbnail",
  "avatars": "avatar",
  "products": "product"
}
'''

# Same remote bucket configuration as remote env
REMOTE_BUCKETS = '''
{
  "default": "https://cdn.erfianugrah.com"
}
'''

# Same path transformations as remote env
PATH_TRANSFORMS = '''
{
  "images": {
    "prefix": "",
    "removePrefix": true
  },
  "assets": {
    "prefix": "img/", 
    "removePrefix": true
  },
  "content": {
    "prefix": "content-images/",
    "removePrefix": true
  }
}
'''

[[env.staging.routes]]
pattern = "staging.images.erfi.dev/*"
zone_id = "d6260a9cd0c27db1e9c0a453b2e4761e"

# Production environment
[env.prod]
name = "prod-resizer"

[env.prod.vars]
ENVIRONMENT = "production"
DEPLOYMENT_MODE = "remote"
VERSION = "1.1.0"
FALLBACK_BUCKET = "https://cdn.erfianugrah.com"

# Centralized logging configuration - minimal for production
LOGGING_CONFIG = '''
{
  "level": "WARN",
  "includeTimestamp": true,
  "enableStructuredLogs": true
}
'''

# Debug headers disabled for production
DEBUG_HEADERS_CONFIG = '''
{
  "enabled": false
}
'''

# Predefined image transformation templates (same as other environments)
DERIVATIVE_TEMPLATES = '''
{
  "header": {
    "width": 1600,
    "height": 73,
    "quality": 80,
    "fit": "scale-down",
    "metadata": "copyright"
  },
  "thumbnail": {
    "width": 320,
    "height": 150,
    "quality": 85,
    "fit": "scale-down",
    "metadata": "copyright",
    "sharpen": 1
  },
  "avatar": {
    "width": 180,
    "height": 180,
    "quality": 90,
    "fit": "cover",
    "metadata": "none",
    "gravity": "face"
  },
  "product": {
    "width": 800,
    "height": 800,
    "quality": 85,
    "fit": "contain",
    "background": "white"
  }
}
'''

# Path-based derivative mappings (same as other environments)
PATH_TEMPLATES = '''
{
  "profile-pictures": "avatar",
  "hero-banners": "header",
  "header": "header",
  "thumbnail": "thumbnail",
  "avatars": "avatar",
  "products": "product"
}
'''

# Same remote bucket configuration as other envs
REMOTE_BUCKETS = '''
{
  "default": "https://cdn.erfianugrah.com"
}
'''

# Same path transformations as other envs
PATH_TRANSFORMS = '''
{
  "images": {
    "prefix": "",
    "removePrefix": true
  },
  "assets": {
    "prefix": "img/", 
    "removePrefix": true
  },
  "content": {
    "prefix": "content-images/",
    "removePrefix": true
  }
}
'''

[[env.prod.routes]]
pattern = "images.erfi.dev/*"
zone_id = "d6260a9cd0c27db1e9c0a453b2e4761e"
