name = "image-resizer"
main = "./resizer.js"
compatibility_date = "2021-09-21"
account_id = "25f21f141824546aa72c74451a11b419"
send_metrics = false

[dev]
port = 9001
local_protocol="http"
upstream_protocol="https"

[env.staging]
name = "staging-resizer"
vars = { ENVIRONMENT = "staging" }
workers_dev = true

[env.prod]
name = "prod-resizer"
vars = { ENVIRONMENT = "production" }
route = { pattern = "erfianugrah.com/content/images/*", zone_id = "3f2c4daa43d5920f313654a873b31d06" }